name: SQL MDF Export

on:
  workflow_dispatch:

jobs:
  build-db:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
      options: --privileged -v /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Install Docker CLI
        run: |
          apt-get update
          apt-get install -y docker.io netcat-openbsd iputils-ping

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run MSBuild SQL Export
        run: |
          dotnet msbuild test-sql.msbuild /t:BuildDatabase

      - name: Upload MDF and LDF
        uses: actions/upload-artifact@v4
        with:
          name: sql-data
          path: ./sqldata/*.mdf,./sqldata/*.ldf
