name: SQL MDF Export

on:
  workflow_dispatch:

jobs:
  build-db:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:24.04

    steps:
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install -y curl apt-transport-https ca-certificates

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run MSBuild SQL Export
        run: |
          dotnet msbuild test-sql.msbuild /t:BuildDatabase

      - name: Upload MDF and LDF
        uses: actions/upload-artifact@v4
        with:
          name: sql-data
          path: ./sqldata/*.mdf,./sqldata/*.ldf
